#
# ChestIcon
#  @author Robby Duke
#  @date   01/09/2015
#

name: 'ChestIcon'
version: 1.1
api-version: '1.16'
description: 'ChestShop integrated implementation of visible item sales.'

author: 'Robby Duke'
authors: ['NoEff3x', 'jacklink01']
website: https://github.com/VoidTeam/chesticon

main: net.voidteam.cicon.ChestIcon
database: false
depend: ['ChestShop', 'ItemStay']